//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    
    public partial class sp_ConsultarPersonasDependeDeTipoDeUsuario_Result1
    {
        public int PersonaIdPersona { get; set; }
        public string PersonaNumeroDocumento { get; set; }
        public string PersonaApellidoPaterno { get; set; }
        public string PersonaApellidoMaterno { get; set; }
        public string PersonaPrimerNombre { get; set; }
        public string PersonaSegundoNombre { get; set; }
        public System.DateTime PersonaFechaCreacion { get; set; }
        public Nullable<System.DateTime> PersonaFechaActualizacion { get; set; }
        public int PersonaIdTipoDocumento { get; set; }
        public bool PersonaEstado { get; set; }
        public int AsignacionTipoUsuarioIdAsignacionTU { get; set; }
        public int AsignacionTipoUsuarioIdTipoUsuario { get; set; }
        public int AsignacionTipoUsuarioIdUsuario { get; set; }
        public System.DateTime AsignacionTipoUsuarioFechaCreacion { get; set; }
        public Nullable<System.DateTime> AsignacionTipoUsuarioFechaActualizacion { get; set; }
        public bool AsignacionTipoUsuarioEstado { get; set; }
        public int TipoUsuarioIdTipoUsuario { get; set; }
        public string TipoUsuarioIdentificacion { get; set; }
        public string TipoUsuarioDescripcion { get; set; }
        public bool TipoUsuarioEstado { get; set; }
    }
}
