//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    
    public partial class sp_ConsultarConfigurarVentaPorIdCabeceraFactura_Result2
    {
        public int IdConfigurarVenta { get; set; }
        public int IdCabeceraFactura { get; set; }
        public int IdPersona { get; set; }
        public bool EstadoConfVenta { get; set; }
        public Nullable<int> IdConfiguracionInteres { get; set; }
        public bool Efectivo { get; set; }
        public Nullable<int> Descuento { get; set; }
        public Nullable<System.DateTime> FechaFinCredito { get; set; }
        public bool AplicaSeguro { get; set; }
        public Nullable<decimal> ValorSeguro { get; set; }
        public Nullable<bool> SeguroCancelado { get; set; }
    }
}
