//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    
    public partial class sp_ConsultarTotalDeFacturasCompradasACreditoPorPersonaEnAnoActual_Result1
    {
        public int IdPersona { get; set; }
        public decimal CANTIDAD_COMPRADA { get; set; }
    }
}
