//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    
    public partial class sp_ConsultarTiposDeUsuariosQueTieneUnUsuario_Result1
    {
        public int AsignacionTipoUsuarioIdAsignacionTU { get; set; }
        public bool AsignacionTipoUsuarioEstado { get; set; }
        public Nullable<System.DateTime> AsignacionTipoUsuarioFechaActualizacion { get; set; }
        public System.DateTime AsignacionTipoUsuarioFechaCreacion { get; set; }
        public int AsignacionTipoUsuarioIdTipoUsuario { get; set; }
        public int AsignacionTipoUsuarioIdUsuario { get; set; }
        public int TipoUsuarioIdTipoUsuario { get; set; }
        public string TipoUsuarioDescripcion { get; set; }
        public bool TipoUsuarioEstado { get; set; }
        public Nullable<System.DateTime> TipoUsuarioFechaActualizacion { get; set; }
        public System.DateTime TipoUsuarioFechaCreacion { get; set; }
        public string TipoUsuarioIdentificacion { get; set; }
    }
}
