//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    
    public partial class sp_ConsultarTickenVentaPorId_Result1
    {
        public int IdVentaRubro { get; set; }
        public string Codigo { get; set; }
        public System.DateTime FechaEntrada { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public int IdPersonaCliente { get; set; }
        public Nullable<int> IdPersonaChofer { get; set; }
        public int IdTipoRubro { get; set; }
        public int IdTipoPresentacionRubro { get; set; }
        public int IdAsignarTU { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
        public Nullable<decimal> PesoTara { get; set; }
        public Nullable<decimal> PesoBruto { get; set; }
        public Nullable<decimal> PrecioPorQuintal { get; set; }
        public Nullable<decimal> PorcentajeImpureza { get; set; }
        public Nullable<decimal> PorcentajeHumedad { get; set; }
        public Nullable<decimal> PesoNeto { get; set; }
        public Nullable<decimal> PesoACobrar { get; set; }
        public Nullable<decimal> TotalACobrar { get; set; }
        public bool Estado { get; set; }
        public bool Anulado { get; set; }
        public Nullable<int> IdAsignarTUAnulado { get; set; }
    }
}
